# replica count for dev
replicaCount: 1

mysql:
  # if use external mysql server, please set true
  #   by default using false, chart will create a single mysql instance
  # TODO(matrixji): add support external mysql server
  useExternal: false

  # the external mysql server address
  externalServer: 127.0.0.1

  # external mysql port
  externalPort: 3306

  # the username for devlake database
  username: merico

  # the password for devlake database
  password: merico

  # the database for devlake
  database: lake

  # root password for mysql, only used when use_external=true
  rootPassword: admin

  # storage for mysql
  storage:
    # the storage class for pv, leave empty will using default
    class: ""
    size: 5Gi

  # image for mysql
  image:
    repository: mysql
    tag: 8.0.26
    pullPolicy: IfNotPresent
  
  # resources config for mysql if have
  resources: {}

  # nodeSelector config for mysql if have
  nodeSelector: {}

  # tolerations config for mysql if have
  tolerations: []

  # affinity config for mysql if have
  affinity: {}


grafana:
  # image for grafana
  image:
    repository: mericodev/grafana
    tag: latest
    pullPolicy: Always
  
  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}


lake:
  image:
    repository: mericodev/lake
    tag: latest
    pullPolicy: Always
  # storage for config
  storage:
    # the storage class for pv, leave empty will using default
    class: ""
    size: 100Mi

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

ui:
  image:
    repository: mericodev/config-ui
    tag: latest
    pullPolicy: Always

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

service:
  type: NodePort
  grafanaPort: 32000
  uiPort: 32001

# TODO(matrixji) support ingress.
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local